dataset_path: /home/pars/mof_synthesis
models:
- model_name: Falcon 7B
  model_path: /home/pars/Coding/falcon-7b/
  model_type: text-generation
extract_config:
  additive:
    type: string
    convert_funcs:
    - ans2cid
    dataset_cols:
    - additive1
  solvent:
    type: string
    convert_funcs:
    - ans2cid
    dataset_cols:
    - solvent1
  temperature:
    type: number
    convert_funcs:
    - ans2temperature
    dataset_cols:
    - temperature_Celsius
  time:
    type: number
    convert_funcs:
    - ans2time
    dataset_cols:
    - time_h
